export type EmployeeLevel = {
    EmployeeKey: string; //"ca499525-203a-4337-b04c-fad4ba6f95c4",
    CompanyEnabled: boolean; //true,
    LocationEnabled: boolean; //false,
    DivisionEnabled: boolean; //false,
    DepartmentEnabled: boolean; //true,
    PositionEnabled: boolean; //false,
    Company: string; //"Startkleen Legacy LLC",
    CompanyId: string; //"70063901",
    CompanyKey: string; //"1c1558c7-6007-4f69-97ee-ac28197bb845",
    Location: string; //"",
    LocationId: string; //"",
    LocationKey: string; //"",
    Division: string; //"",
    DivisionId: string; //"",
    DivisionKey: string; //"",
    Department: string; //"BMD Buckhead Meat Of Dallas",
    DepartmentId: string; //"BMD",
    DepartmentKey: string; //"9401bf9d-ce22-4849-b2e2-9a2b1a26a6c8",
    Position: string; //"",
    PositionId: string; //"",
    PositionKey: string; //""
}